### ISSUE TITLE
unable to add multiple recipients

### ISSUE THREAD

**Issue by bhaveshlakhotia** [Azure/Microsoft365R#161] opened 2023-05-26 16:58 UTC
Hi,

I am getting an error when i am trying to append multiple recipients. I am wondering this is arising from the build_email_recipients. i have used the latest version from CRAN

Error in !is_empty(addr_list) && is.na(addr_list) : 
  'length = 2' in coercion to 'logical(1)'

**Comment by hongooi73** [comment] 2023-05-27 00:14
Duplicate of #151, #134. Use the dev version until it gets updated on CRAN

**Closed by hongooi73** 2023-05-27 00:14 UTC

**Comment by hongooi73** [comment] 2023-06-01 00:49
Fix is now on CRAN
