### ISSUE TITLE
Upload a New Folder / Create an exisiting Folder

### ISSUE THREAD

**Issue by msgoussi** [Azure/Microsoft365R#112] opened 2022-04-09 14:58 UTC
1. I am wondering if there is a function to upload a folder with all its files in sharepoint.

2. Also I get an error when i want to create an existing folder in the sharepoint
Error in process_response(res, match.arg(http_status_handler), simplify) : 
  Conflict (HTTP 409). Failed to complete operation. Message:
The specified item name already exists.

I am wondering if it shows a warning instead of error.

**Comment by hongooi73** [comment] 2022-04-09 15:56
Duplicate of #19

Re 2), the error is what is returned from the API. You can always wrap the `create_folder` call inside a `try`.

**Closed by hongooi73** 2022-04-09 15:56 UTC
