### ISSUE TITLE
Is it possible to access Outlook calendar data with this package?

### ISSUE THREAD

**Issue by IISimonII** [Azure/Microsoft365R#178] opened 2023-07-24 23:10 UTC
Is it possible to access Outlook calendar data with this package in R? I would love to be able to download and analyze Outlook calendar data to calculate statistics on time usage and from there write reports.

**Comment by hongooi73** [comment] 2023-09-10 02:03
Duplicate of #98

Not yet, but if there's enough demand I might have a look at it

**Closed by hongooi73** 2023-09-10 02:03 UTC
