### ISSUE TITLE
Error in Adding Multiple Recipients (Business and Personal Outlook)

### ISSUE THREAD

**Issue by JSWP2015** [Azure/Microsoft365R#151] opened 2023-05-10 16:30 UTC
Hi all,

PREFACE: Removed/Edited personal and business email addresses for privacy concerns

I'm seeing an error regarding a conversion from length(2) coercion to a logical(1) seen in the code below - I believe this may have something to do with a && operator in the addr_list portion of the function (based on some **very** light reading), but not entirely sure - the code below shows what I'm seeing with the error written in. Thanks!

##################################################################################
# Setting Environments
personal <- get_personal_outlook()
business <- get_business_outlook(tenant = tenant$Value)

# Create Email
mail <- personal$create_email()
bizMail <- business$create_email()

# Clearing Recipients
mail$set_recipients()
bizMail$set_recipients()
##################################################################################
# Test 1: Add Recipients Method, One by One
mail$set_body('test')
mail$set_subject('test subject')
mail$add_recipients('help@business.com')
mail$add_recipients('mypersonalemail@gmail.com')

Error at Second Add Recipients : 
Error in !is_empty(addr_list) && is.na(addr_list) : 'length = 2' in coercion to 'logical(1)'
##################################################################################
# Resetting
mail <- personal$create_email()
mail$set_recipients()
##################################################################################
# Test 2: Set Recipients Method, Bulk
mail <- personal$create_email()
mail$set_body('test2')
mail$set_subject('test2 subject')
mail$set_recipients()
mail$set_recipients(c('help@business.com','mypersonalemail@gmail.com'))

Error at Adding Two Recipients 
Error in !is_empty(addr_list) && is.na(addr_list) : 'length = 2' in coercion to 'logical(1)'

##################################################################################
# Test 3: Business One by One and Bulk 
bizMail$set_body('test')
bizMail$set_subject('test subject')
bizMail$add_recipients('help@business.com')
bizMail$add_recipients('mypersonalemail@gmail.com')

Error at Second Add Recipients 
Error in !is_empty(addr_list) && is.na(addr_list) : 'length = 2' in coercion to 'logical(1)'

##################################################################################
# Resetting
bizMail <- business$create_email()
bizMail$set_recipients()
##################################################################################
# Test Second Time
bizMail <- business$create_email()
bizMail$set_body('test2')
bizMail$set_subject('test2 subject')
bizMail$set_recipients()
bizMail$set_recipients(c('help@business.com','mypersonalemail@gmail.com'))

Error at Set Recipients 
Error in !is_empty(addr_list) && is.na(addr_list) : 'length = 2' in coercion to 'logical(1)'

##################################################################################

**Comment by msberends** [comment] 2023-05-11 18:12
Yes, welcome to R 4.3. Since that update, this throws an error - previously it was 'only' a warning.

Fix is proposed in #152, so merging that PR should solve it.

**Comment by hongooi73** [comment] 2023-05-12 06:20
This should be fixed in the dev branch. Let me know if it still breaks.

**Comment by hongooi73** [comment] 2023-05-12 06:22
duplicate of #134

**Closed by hongooi73** 2023-05-12 06:22 UTC
