### ISSUE TITLE
File contentUrl extension: '.csv&action=default&mobileredirect=true' and name extension: '.csv' do not match.

### ISSUE THREAD

**Issue by feddelegrand7** [Azure/Microsoft365R#86] opened 2021-09-21 07:19 UTC
Hi, thank you for the great package. I've only one problem, using the `send_message` method I can for example send `jpg` files but when I try with a `csv` file I got the following Error: 
 
```
Error in process_response(res, match.arg(http_status_handler), simplify) : 
  Bad Request (HTTP 400). Failed to complete operation. Message:
File contentUrl extension:
'.csv&action=default&mobileredirect=true'
and name extension: '.csv' do not match.
```
Below the code that I used: 
```
team <- Microsoft365R::get_team("team")
  
 channel <- team$get_channel("channel")
  
  channel$send_message(
    body = "something", 
    attachment = "mtcars.csv"
  )
```

I need to mention that the same happens with `.doc` Word document extensions. Is there a config that I need to do? 
Thank you again.

**Comment by hongooi73** [comment] 2021-09-21 08:19
Duplicate of #73, fixed in next release

**Closed by hongooi73** 2021-09-21 08:19 UTC

**Comment by feddelegrand7** [comment] 2021-09-21 09:03
Perfect, thank you @hongooi73
